#!/usr/bin/env lua
-- sketchybar-v2.22.0

-- Load the sketchybar-package and prepare the helper binaries
require("helpers")
require("init")

-- Enable hot reloading
sbar.exec("sketchybar --hotload true")

