#!/usr/bin/env sh

############## IMPORT ##############
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
SCRIPT_DIR="$CONFIG_DIR/.scripts"

FONT="JetBrainsMono Nerd Font"
ICON_FONT="JetBrainsMono Nerd Font"

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

PADDING=6
############## BAR APPEARANCE  ##############
sketchybar --bar position=top \
        height=32 \
        blur_radius=30 \
        color=${background} \
        corner_radius 10

############## GLOBAL DEFAULTS ##############
default=(
  padding_left=5
  padding_right=5
  icon.font="$FONT:Bold:14.0"
  label.font="$ICON_FONT:Bold:14.0"
  icon.highlight_color="${comment}" \
  icon.color=${foreground}
  label.color=${foreground}
  icon.padding_left=$PADDING
  icon.padding_right=$PADDING
  label.padding_left=$PADDING
  label.padding_right=$PADDING
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
##### LEFT ITEMS #####
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"

##### RIGHT ITEMS #####
source "$ITEM_DIR/battery.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --hotload on
sketchybar --update