#!/usr/bin/env sh

# Load Yabai scripting addition
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Function to apply Yabai configuration settings
apply_yabai_config() {
  local yabai_config=(
    -m config

    layout bsp
    auto_balance off
    split_ratio 0.50

    insert_feedback_color 0xffbd93f9

    mouse_follows_focus on
    mouse_modifier ctrl
    mouse_action1 move
    mouse_action2 resize
    mouse_drop_action swap

    top_padding 10
    bottom_padding 10
    left_padding 10
    right_padding 10
    window_gap 10
    external_bar all:36:0

    window_opacity on
    window_opacity_duration 0.5
    active_window_opacity 0.98
    normal_window_opacity 0.80

    window_placement second_child
    window_shadow on
    window_zoom_persist off
    window_animation_duration 0.1
    window_animation_easing ease_out_quint
  )

  yabai "${yabai_config[@]}"
}

# Function to add application-specific rules
add_yabai_rules() {
  # Exclude specific applications from being opacified
  # yabai -m rule --add app="^Arc$" opacity=1.0
  # yabai -m rule --add app="^Zen Browser$" opacity=1.0
  # yabai -m rule --add app="^Figma$" opacity=1.0

  # Exclude specific windows by title
  # find windows with yabai -m query --windows | jq
  # custom rules for Jetbrains Software
  jetbrains_exclude_titles=(
    "^Data Sources and Drivers$"
    "^Welcome to.*$"
    "^NPM Script$"
    "^Keymap$"
    "^Tip of the Day$"
    "^Settings$"
    "^Run\/Debug Configurations$"
    "^Push Commits to.*$"
    "^Add File to Git$"
    "^Copy$"
    "^Rename$"
    "^Composer$"
    "^Delete$"
  )
  for app_tittle in "${jetbrains_exclude_titles[@]}"; do
    yabai -m rule --add app="PhpStorm" title="$app_tittle" manage=off
    yabai -m rule --add app="CLion" title="$app_tittle" manage=off
  done

  yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off

  yabai -m rule --add app="Brave Browser" title="^Acceso:.*$" manage=off
  yabai -m rule --add label="Brave Browser" app="^Brave Browser$" title="^Acceso:.*$" manage=off

  yabai -m rule --add app="Spotify" title="^Spotify Premium$" manage=off
  yabai -m rule --add label="Spotify" app="^Spotify$" title="Spotify Premium" manage=off

  yabai -m rule --add app="Finder" title="^Copy$" manage=off
  yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off

  yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
  # relate apps to spaces
  # yabai -m rule --add app="Spotify" space=3
  # Exclude specific applications from being managed
   apps_to_exclude=(
     "^Calculator$"
     "^Software Update$"
     "^Spotify$"
     "^Reminders$"
     "^Dictionary$"
     "^System Preferences$"
     "^System Settings$"
     "^Archive Utility$"
     "^App Store$"
     "^Raycast$"
     "^Activity Monitor$"
     "^Notion Calendar$"
     "^Tuple$"
     "^Messages$"
     "^Logi Options+$"
     "^Logi Options+ Installer$"
     "^Docker Desktop$"
     "^Mail$"
   )

   for app in "${apps_to_exclude[@]}"; do
     yabai -m rule --add app="$app" manage=off
   done
}

# Apply configuration and rules
apply_yabai_config
add_yabai_rules
echo "yabai configuration loaded.."
