#!/usr/bin/env sh

# Load Yabai scripting addition
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Function to apply Yabai configuration settings
apply_yabai_config() {
  local yabai_config=(
    -m config

    layout bsp
    auto_balance off
    split_ratio 0.50

    insert_feedback_color 0xffbd93f9

    focus_follows_mouse off
    mouse_follows_focus on
    mouse_modifier ctrl
    mouse_action1 move
    mouse_action2 resize
    mouse_drop_action swap

    top_padding 8
    bottom_padding 8
    left_padding 8
    right_padding 9
    window_gap 8
    external_bar all:36:0

    active_window_opacity 0.95
    normal_window_opacity 0.8

    window_placement second_child
    window_shadow float
    window_opacity on
    window_opacity_duration 0.2

    window_zoom_persist off
    window_animation_duration 0.3
    window_animation_easing ease_out_quint
  )

  yabai "${yabai_config[@]}"
}

# Function to add application-specific rules
add_yabai_rules() {
  # Exclude specific applications from being opacified
  yabai -m rule --add app="^Arc$" opacity=1.0
  yabai -m rule --add app="^Zen Browser$" opacity=1.0
  yabai -m rule --add app="^Figma$" opacity=1.0

  # Exclude specific windows by title
  # yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
  # yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
  # yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
  # yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

  # yabai -m rule --add label="PhpStorm" app="^Php Storm$" title="(Welcome to PhpStorm|Settings)" manage=off

  # Exclude specific applications from being managed
   apps_to_exclude=(
     "^Calculator$"
     "^Software Update$"
     "^Dictionary$"
     "^System Preferences$"
     "^System Settings$"
     "^Archive Utility$"
     "^App Store$"
     "^Raycast$"
     "^Activity Monitor$"
     "^Notion Calendar$"
     "^Tuple$"
     "^Messages$"
     "^Logi Options+$"
     "^Mail$"
   )

   for app in "${apps_to_exclude[@]}"; do
     yabai -m rule --add app="$app" manage=off
   done
}

# Apply configuration and rules
apply_yabai_config
add_yabai_rules
borders active_color=0xffbd93f9 inactive_color=0xfff8f8f2 width=4.0 &
echo "yabai configuration loaded.."
