#!/usr/bin/env sh
# shd-v0.3.9

# moves focus between windows in the current focused display
alt - j : yabai -m window --focus west
alt - k : yabai -m window --focus south
alt - i : yabai -m window --focus north
alt - l : yabai -m window --focus east

# moves focus between spaces
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4
alt - 5 : yabai -m space --focus 5
alt - 6 : yabai -m space --focus 6
alt - 7 : yabai -m space --focus 7
alt - 8 : yabai -m space --focus 8
alt - 9 : yabai -m space --focus 9
alt - 0 : yabai -m space --focus 10

# focus monitor/displays
# ctrl + alt - x  : yabai -m display --focus recent
cmd + alt - j  : yabai -m display --focus prev
cmd + alt - l  : yabai -m display --focus next
cmd + alt - 1  : yabai -m display --focus 1
cmd + alt - 2  : yabai -m display --focus 2
cmd + alt - 3  : yabai -m display --focus 3

# delete focused space
cmd + alt - q : yabai -m space --destroy

# toggle window split type
alt - e : yabai -m window --toggle split

# close window and focus recent(last) windows on focus
alt - x : yabai -m window --close && yabai -m window --focus recent

# minimize window
alt - m : yabai -m window --minimize

# rotate tree
alt - r : yabai -m space --rotate 90

# mirror tree y-axis
alt - y : yabai -m space --mirror y-axis

# toggle desktop offset
alt - a : yabai -m space --toggle padding; yabai -m space --toggle gap

# toggle window parent zoom
alt - d : yabai -m window --focus mouse && \
          yabai -m window --toggle zoom-parent

# float / unfloat window and center on screen
alt - t : yabai -m window --toggle float;\
          yabai -m window --grid 4:4:1:1:2:2

# toggle window fullscreen zoom
alt - f : yabai -m window --focus mouse && \
          yabai -m window --toggle zoom-fullscreen

# toggle window native fullscreen
shift + alt - f : yabai -m window --toggle native-fullscreen

# increase gap in focused space
alt - g : yabai -m space --gap rel:10

# decrease gap in focused space
shift + alt - g : yabai -m space --gap rel:-10

# create a new space and follow focus
alt - n : yabai -m space --create && \
                  index="$(yabai -m query --displays --display | jq '.spaces[-1]')" && \
                  yabai -m space --focus "${index}"

# create a new space, move window and follow focus
shift + alt - n : yabai -m space --create && \
                  index="$(yabai -m query --displays --display | jq '.spaces[-1]')" && \
                  yabai -m window --space "${index}" && \
                  yabai -m space --focus "${index}"

# balance size of windows
shift + alt - 0 : yabai -m space --balance

# swap window
shift + alt - j : yabai -m window --swap west
shift + alt - k : yabai -m window --swap south
shift + alt - i : yabai -m window --swap north
shift + alt - l : yabai -m window --swap east

# move window
shift + cmd - j : yabai -m window --warp west
shift + cmd - k : yabai -m window --warp south
shift + cmd - i : yabai -m window --warp north
shift + cmd - l : yabai -m window --warp east

# send window to a space
shift + alt - 1 : yabai -m window --space 1 && yabai -m space --focus 1
shift + alt - 2 : yabai -m window --space 2 && yabai -m space --focus 2
shift + alt - 3 : yabai -m window --space 3 && yabai -m space --focus 3
shift + alt - 4 : yabai -m window --space 4 && yabai -m space --focus 4
shift + alt - 5 : yabai -m window --space 5 && yabai -m space --focus 5
shift + alt - 6 : yabai -m window --space 6 && yabai -m space --focus 6
shift + alt - 7 : yabai -m window --space 7 && yabai -m space --focus 7
shift + alt - 8 : yabai -m window --space 8 && yabai -m space --focus 8
shift + alt - 9 : yabai -m window --space 9 && yabai -m space --focus 9
shift + alt - 0 : yabai -m window --space 10 && yabai -m space --focus 10

# change layout of desktop
ctrl + alt - a : yabai -m space --layout bsp
ctrl + alt - d : yabai -m space --layout float

# increase window size
ctrl + alt - j : yabai -m window --resize left:-20:0  yabai -m window --resize right:-20:0
ctrl + alt - k : yabai -m window --resize bottom:0:20  yabai -m window --resize top:0:20
ctrl + alt - i : yabai -m window --resize top:0:-20  yabai -m window --resize bottom:0:-20
ctrl + alt - l : yabai -m window --resize right:20:0  yabai -m window --resize left:20:0

# decrease window size
#ctrl + alt + cmd - j : yabai -m window --resize left:40:0
#ctrl + alt + cmd - k : yabai -m window --resize bottom:0:-40
#ctrl + alt + cmd - i : yabai -m window --resize top:0:40
#ctrl + alt + cmd - l : yabai -m window --resize right:-40:0

# https://github.com/koekeishiya/yabai/issues/200#issuecomment-519257233
#ctrl + cmd - h : yabai -m window --resize left:-20:0 ; yabai -m window --resize right:-20:0
#ctrl + cmd - j : yabai -m window --resize bottom:0:20 ; yabai -m window --resize top:0:20
#ctrl + cmd - k : yabai -m window --resize top:0:-20 ; yabai -m window --resize bottom:0:-20
#ctrl + cmd - l : yabai -m window --resize right:20:0 ; yabai -m window --resize left:20:0

# restart yabai
#ctrl + alt + cmd - r : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"
# e.g. bind to key in skhd:
ctrl + alt + cmd - r : yabai --restart-service
