#!/usr/bin/env sh

# change window focus within space
alt - k : yabai -m window --focus south
alt - i : yabai -m window --focus north
alt - j : yabai -m window --focus west
alt - l : yabai -m window --focus east

#change focus between external displays (left and right)
alt - a: yabai -m display --focus west
alt - d: yabai -m display --focus east
	

# rotate layout clockwise
shift + alt - r : yabai -m space --rotate 270

# flip along y-axis
shift + alt - y : yabai -m space --mirror y-axis
# flip along x-axis
shift + alt - x : yabai -m space --mirror x-axis
# toggle window float
shift + alt - t : yabai -m window --toggle float --grid 4:4:1:1:2:2

# swap windows
shift + alt - k : yabai -m window --swap south
shift + alt - i : yabai -m window --swap north
shift + alt - j : yabai -m window --swap west
shift + alt - l : yabai -m window --swap east

# move window and split
ctrl + alt - k : yabai -m window --warp south
ctrl + alt - i : yabai -m window --warp north
ctrl + alt - j : yabai -m window --warp west
ctrl + alt - l : yabai -m window --warp east

# move window to display left and right
shift + alt - a : yabai -m window --display west; yabai -m display --focus west;
shift + alt - d : yabai -m window --display east; yabai -m display --focus east;

# move window to space #
shift + alt - 1 : yabai -m window --space 1;
shift + alt - 2 : yabai -m window --space 2;
shift + alt - 3 : yabai -m window --space 3;
shift + alt - 4 : yabai -m window --space 4;
shift + alt - 5 : yabai -m window --space 5;
shift + alt - 6 : yabai -m window --space 6;
shift + alt - 7 : yabai -m window --space 7;

echo "skhdrc configuration loaded.."