#!/bin/bash

options=(
	# style=round
	width=5.0
	hidpi=off
	active_color="gradient(top_left=0xffbd93f9,bottom_right=0xffff79c6)"
	inactive_color=0xff6272a4
    background_color=0x00282a36
    blur_radius=24
)

borders "${options[@]}"
